In [55]:
import pandas as pd
import numpy as np
import sys

import warnings
import math

df=pd.read_csv('../data/data.csv.gz', compression='gzip', sep=',')
df['timestamp'] = pd.to_datetime(df['time_stamp'], format="%Y-%m-%d %H:%M:%S").dt.tz_convert('CET')

In [56]:
stock_delta = df['stock_id'] - df['stock_id'].shift()
time_delta = (df['timestamp'] - df['timestamp'].shift()).fillna(10000).dt.total_seconds()

/home/ken/.local/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: Passing integers to fillna is deprecated, will raise a TypeError in a future version.  To retain the old behavior, pass pd.Timedelta(seconds=n) instead.

In [57]:
stock_split_index=df.index[stock_delta!=0].tolist()
stock_split_index.append(len(df))

In [58]:
day_split_index=df.index[abs(time_delta)>36000].tolist()
day_split_index.insert(0, 0)
day_split_index.append(len(df))

In [59]:
stock_id_list = df['stock_id'].unique().tolist()
i = 0
for stock_index in stock_id_list:
    
    print("index: {}, id:{}".format(i, stock_index))
    i+=1

index: 0, id:101
index: 1, id:1027
index: 2, id:120
index: 3, id:139301
index: 4, id:15285
index: 5, id:160271
index: 6, id:161
index: 7, id:18634
index: 8, id:281
index: 9, id:283
index: 10, id:285
index: 11, id:300
index: 12, id:323
index: 13, id:340
index: 14, id:3524
index: 15, id:361
index: 16, id:366
index: 17, id:3966
index: 18, id:401
index: 19, id:402
index: 20, id:45
index: 21, id:46
index: 22, id:47
index: 23, id:4928
index: 24, id:5095
index: 25, id:81
index: 26, id:812
index: 27, id:819
index: 28, id:992
index: 29, id:999

In [60]:
current_stock_index = 0
time_series_list = []
time_series_all_list = []
for i in range(len(day_split_index) - 1):
    start_index = day_split_index[i]
    end_index = day_split_index[i + 1]
    day_time_series = df.iloc[start_index:end_index]
    time_series_list.append(day_time_series)
    if end_index == stock_split_index[current_stock_index + 1]:
        print("finished stock: {}, got {} time series".format(current_stock_index, len(time_series_list)))
        time_series_all_list.append(time_series_list)
        time_series_list = []
        current_stock_index += 1

finished stock: 0, got 63 time series
finished stock: 1, got 63 time series
finished stock: 2, got 63 time series
finished stock: 3, got 63 time series
finished stock: 4, got 63 time series
finished stock: 5, got 63 time series
finished stock: 6, got 63 time series
finished stock: 7, got 63 time series
finished stock: 8, got 63 time series
finished stock: 9, got 63 time series
finished stock: 10, got 63 time series
finished stock: 11, got 63 time series
finished stock: 12, got 63 time series
finished stock: 13, got 63 time series
finished stock: 14, got 63 time series
finished stock: 15, got 63 time series
finished stock: 16, got 63 time series
finished stock: 17, got 63 time series
finished stock: 18, got 63 time series
finished stock: 19, got 63 time series
finished stock: 20, got 63 time series
finished stock: 21, got 63 time series
finished stock: 22, got 63 time series
finished stock: 23, got 63 time series
finished stock: 24, got 63 time series
finished stock: 25, got 63 time series
finished stock: 26, got 63 time series
finished stock: 27, got 63 time series
finished stock: 28, got 63 time series
finished stock: 29, got 63 time series

In [61]:
for stock_id in range(len(stock_id_list)):
    diff = time_series_all_list[stock_id][0]['open'].diff()

    min_ = diff[diff>=0.005].min()
    open_ = time_series_all_list[stock_id][0]['open'].mean()

    print("stockid:{} min={}, cost={}".format(stock_id, min_, min_/open_))

stockid:0 min=0.01999999999999602, cost=0.0002506328731686442
stockid:1 min=0.04999999999999716, cost=0.0004324118086577501
stockid:2 min=0.09999999999999432, cost=0.0004770512691615322
stockid:3 min=0.05000000000001137, cost=0.00022208616640416757
stockid:4 min=0.04999999999998295, cost=0.0002296265100385087
stockid:5 min=0.009999999999990905, cost=0.00012077163935460391
stockid:6 min=0.0999999999999659, cost=0.0002550752396191084
stockid:7 min=0.04999999999998295, cost=0.00025107768120267684
stockid:8 min=0.01999999999999602, cost=0.00021859492554106004
stockid:9 min=0.04999999999998295, cost=0.0003103472424430125
stockid:10 min=0.04999999999998295, cost=0.0003345156164678929
stockid:11 min=0.00999999999999801, cost=0.0003036286812322899
stockid:12 min=0.01999999999999602, cost=0.00025655061972493324
stockid:13 min=0.01999999999999602, cost=0.00020031162457892878
stockid:14 min=0.09999999999990905, cost=0.00015461811402305147
stockid:15 min=0.0999999999999659, cost=0.0002516653539310279
stockid:16 min=0.04999999999999716, cost=0.00040022399230502613
stockid:17 min=0.04999999999998295, cost=0.0002882983652986772
stockid:18 min=0.04999999999998295, cost=0.0003441124545689826
stockid:19 min=0.04999999999998295, cost=0.0002992523993222995
stockid:20 min=0.04999999999998295, cost=0.00021194444432686026
stockid:21 min=0.04999999999998295, cost=0.00023062060290126194
stockid:22 min=0.1999999999999318, cost=0.000274997294775039
stockid:23 min=0.04999999999998295, cost=0.0003484499688678757
stockid:24 min=0.00999999999999801, cost=0.00025275447209916586
stockid:25 min=0.09999999999999432, cost=0.0004798826713827897
stockid:26 min=0.01999999999999602, cost=0.00023707653763174866
stockid:27 min=0.0999999999999659, cost=0.0002253572128512553
stockid:28 min=0.01999999999998181, cost=0.00014791440686309394
stockid:29 min=0.09999999999999432, cost=0.0004442917059851916

In [63]:
for stock_id in range(len(time_series_all_list)):
    print("handling stock_id: {}".format(stock_id))
    for day_id in range(len(time_series_all_list[stock_id])):
        # :-1 is that we don't like the last record at 17:30 which is a aggregated number.
        df = time_series_all_list[stock_id][day_id]
        # some data might miss, we must make a right join with full time series
        # and do fillna.
        df2 = df.set_index('timestamp')
        ts = df2.index.min()
        start_time_str = "{}-{:02d}-{:02d} 8:54:00".format(ts.year, ts.month, ts.day)
        start_ts = pd.Timestamp(start_time_str, tz=ts.tz)
        # periods=510 means from 9 to 17.29
        dti = pd.date_range(start_ts , periods=516, freq='min').to_series(keep_tz=True).rename('time')
        # remove from 17.25 - 17.28
        #dti.drop(dti.tail(5).head(4).index, inplace=True)
        df3 = df2.join(dti, how='right')
        if day_id == 0: # the first day, we must set the value from 8.55-8.59 as same as 9.00
            df3['last'].iloc[0] = df3['last'].iloc[5]
        else:
            df3['last'].iloc[0] = time_series_all_list[stock_id][day_id-1]['last'].iloc[-1]
        
        
        df3['last'].interpolate(method='linear', inplace=True)
        df3['volume'].iloc[:6] = df3['volume'].iloc[6] / 6
        df3['volume'].iloc[6] = df3['volume'].iloc[6] / 6
        df3['volume'].iloc[-5:] = df3['volume'].iloc[-1]/5
        
        
        df = df3.reset_index().rename({'index':'timestamp'}, axis=1)
        #df['timestamp'] = pd.to_datetime(df['time_stamp'], format="%Y-%m-%d %H:%M:%S").dt.tz_convert('Europe/Stockholm')
        df['ema_10'] = df['last'].ewm(span=10, adjust=False).mean()
        df['ema_20'] = df['last'].ewm(span=20, adjust=False).mean()
        df['diff_ema_10']=(df['ema_10'].diff()[1:]/df['ema_10']).fillna(0)
        # the first diff at 9:00 is the difference between today's open and yesterday's last.

        df['diff_ema_20']=(df['ema_20'].diff()[1:]/df['ema_20']).fillna(0)
        df['value_ema_10_beta_99'] = 0
        df['value_ema_20_beta_99'] = 0
        df['value_ema_10_beta_98'] = 0
        df['value_ema_20_beta_98'] = 0
        for iter_id in range(10):
            df['value_ema_10_beta_99'] = df['diff_ema_10'].shift(-1).fillna(0) + \
                0.99 * df['value_ema_10_beta_99'].shift(-1).fillna(0)
            df['value_ema_10_beta_98'] = df['diff_ema_10'].shift(-1).fillna(0) + \
                0.98 * df['value_ema_10_beta_98'].shift(-1).fillna(0)
            df['value_ema_20_beta_99'] = df['diff_ema_20'].shift(-1).fillna(0) + \
                0.99 * df['value_ema_20_beta_99'].shift(-1).fillna(0)
            df['value_ema_20_beta_98'] = df['diff_ema_20'].shift(-1).fillna(0) + \
                0.98 * df['value_ema_20_beta_98'].shift(-1).fillna(0)
        # drop the first row because diff is nan    
        #df.drop(0, inplace=True)
        time_series_all_list[stock_id][day_id] = df.fillna(0)

handling stock_id: 0
handling stock_id: 1
handling stock_id: 2
handling stock_id: 3
handling stock_id: 4
handling stock_id: 5
handling stock_id: 6
handling stock_id: 7
handling stock_id: 8
handling stock_id: 9
handling stock_id: 10
handling stock_id: 11
handling stock_id: 12
handling stock_id: 13
handling stock_id: 14
handling stock_id: 15
handling stock_id: 16
handling stock_id: 17
handling stock_id: 18
handling stock_id: 19
handling stock_id: 20
handling stock_id: 21
handling stock_id: 22
handling stock_id: 23
handling stock_id: 24
handling stock_id: 25
handling stock_id: 26
handling stock_id: 27
handling stock_id: 28
handling stock_id: 29

In [65]:
columns = ['timestamp','last', 'diff_ema_20', 'value_ema_20_beta_99', 'value_ema_20_beta_98', 
           'diff_ema_10', 'value_ema_10_beta_99', 'value_ema_10_beta_98', 'volume']

                    timestamp       last  diff_ema_20  value_ema_20_beta_99  \
0   2019-01-29 08:54:00+01:00  79.020000     0.000000              0.000853
1   2019-01-29 08:55:00+01:00  79.033333     0.000016              0.000942
2   2019-01-29 08:56:00+01:00  79.046667     0.000031              0.001008
3   2019-01-29 08:57:00+01:00  79.060000     0.000044              0.001185
4   2019-01-29 08:58:00+01:00  79.073333     0.000056              0.001420
5   2019-01-29 08:59:00+01:00  79.086667     0.000066              0.001444
6   2019-01-29 09:00:00+01:00  79.100000     0.000076              0.001341
7   2019-01-29 09:01:00+01:00  79.040000    -0.000003              0.001255
8   2019-01-29 09:02:00+01:00  79.260000     0.000262              0.000910
9   2019-01-29 09:03:00+01:00  79.200000     0.000165              0.000779
10  2019-01-29 09:04:00+01:00  79.240000     0.000197              0.000721
11  2019-01-29 09:05:00+01:00  79.180000     0.000106              0.000698
12  2019-01-29 09:06:00+01:00  79.180000     0.000096              0.000699
13  2019-01-29 09:07:00+01:00  79.300000     0.000231              0.000621
14  2019-01-29 09:08:00+01:00  79.380000     0.000305              0.000431
15  2019-01-29 09:09:00+01:00  79.220000     0.000084              0.000365
16  2019-01-29 09:10:00+01:00  79.120000    -0.000044              0.000514
17  2019-01-29 09:11:00+01:00  79.060000    -0.000112              0.000723
18  2019-01-29 09:12:00+01:00  79.060000    -0.000102              0.000959
19  2019-01-29 09:13:00+01:00  79.160000     0.000028              0.001033
20  2019-01-29 09:14:00+01:00  79.260000     0.000146              0.000957
21  2019-01-29 09:15:00+01:00  79.220000     0.000084              0.000981
22  2019-01-29 09:16:00+01:00  79.240000     0.000100              0.000871
23  2019-01-29 09:17:00+01:00  79.300000     0.000163              0.000741
24  2019-01-29 09:18:00+01:00  79.280000     0.000123              0.000670
25  2019-01-29 09:19:00+01:00  79.200000     0.000015              0.000680
26  2019-01-29 09:20:00+01:00  79.280000     0.000110              0.000616
27  2019-01-29 09:21:00+01:00  79.280000     0.000099              0.000513
28  2019-01-29 09:22:00+01:00  79.320000     0.000138              0.000305
29  2019-01-29 09:23:00+01:00  79.300000     0.000101              0.000140
..                        ...        ...          ...                   ...
486 2019-01-29 17:00:00+01:00  79.940000    -0.000069              0.001265
487 2019-01-29 17:01:00+01:00  80.020000     0.000033              0.001463
488 2019-01-29 17:02:00+01:00  80.040000     0.000054              0.001642
489 2019-01-29 17:03:00+01:00  80.080000     0.000096              0.001760
490 2019-01-29 17:04:00+01:00  80.120000     0.000135              0.001820
491 2019-01-29 17:05:00+01:00  80.100000     0.000098              0.002010
492 2019-01-29 17:06:00+01:00  80.160000     0.000160              0.002114
493 2019-01-29 17:07:00+01:00  80.240000     0.000240              0.002092
494 2019-01-29 17:08:00+01:00  80.260000     0.000241              0.002051
495 2019-01-29 17:09:00+01:00  80.180000     0.000123              0.002176
496 2019-01-29 17:10:00+01:00  80.220000     0.000159              0.002201
497 2019-01-29 17:11:00+01:00  80.300000     0.000239              0.002195
498 2019-01-29 17:12:00+01:00  80.320000     0.000240              0.002232
499 2019-01-29 17:13:00+01:00  80.320000     0.000217              0.002182
500 2019-01-29 17:14:00+01:00  80.320000     0.000196              0.002052
501 2019-01-29 17:15:00+01:00  80.420000     0.000296              0.001780
502 2019-01-29 17:16:00+01:00  80.420000     0.000268              0.001499
503 2019-01-29 17:17:00+01:00  80.400000     0.000218              0.001233
504 2019-01-29 17:18:00+01:00  80.400000     0.000198              0.000956
505 2019-01-29 17:19:00+01:00  80.460000     0.000250              0.000598
506 2019-01-29 17:20:00+01:00  80.420000     0.000179              0.000423
507 2019-01-29 17:21:00+01:00  80.480000     0.000233              0.000192
508 2019-01-29 17:22:00+01:00  80.540000     0.000282             -0.000090
509 2019-01-29 17:23:00+01:00  80.460000     0.000160             -0.000253
510 2019-01-29 17:24:00+01:00  80.380000     0.000050             -0.000306
511 2019-01-29 17:25:00+01:00  80.348000     0.000007             -0.000316
512 2019-01-29 17:26:00+01:00  80.316000    -0.000031             -0.000287
513 2019-01-29 17:27:00+01:00  80.284000    -0.000066             -0.000223
514 2019-01-29 17:28:00+01:00  80.252000    -0.000098             -0.000127
515 2019-01-29 17:29:00+01:00  80.220000    -0.000127              0.000000

     value_ema_20_beta_98  diff_ema_10  value_ema_10_beta_99  \
0                0.000799     0.000000              0.001365
1                0.000888     0.000031              0.001442
2                0.000955     0.000056              0.001478
3                0.001122     0.000076              0.001730
4                0.001343     0.000093              0.002079
5                0.001373     0.000107              0.002005
6                0.001286     0.000118              0.001706
7                0.001222    -0.000041              0.001476
8                0.000895     0.000472              0.000778
9                0.000768     0.000248              0.000551
10               0.000705     0.000295              0.000482
11               0.000681     0.000103              0.000481
12               0.000680     0.000085              0.000523
13               0.000593     0.000345              0.000406
14               0.000396     0.000466              0.000083
15               0.000332     0.000014              0.000019
16               0.000475    -0.000218              0.000367
17               0.000683    -0.000317              0.000793
18               0.000915    -0.000259              0.001231
19               0.000989     0.000018              0.001321
20               0.000917     0.000244              0.001125
21               0.000940     0.000108              0.001141
22               0.000840     0.000134              0.000900
23               0.000714     0.000247              0.000648
24               0.000645     0.000157              0.000528
25               0.000660    -0.000056              0.000575
26               0.000597     0.000138              0.000470
27               0.000501     0.000113              0.000301
28               0.000303     0.000184             -0.000057
29               0.000146     0.000105             -0.000306
..                    ...          ...                   ...
486              0.001198    -0.000080              0.002155
487              0.001387     0.000117              0.002370
488              0.001561     0.000141              0.002547
489              0.001675     0.000206              0.002606
490              0.001735     0.000259              0.002568
491              0.001917     0.000167              0.002794
492              0.002017     0.000273              0.002849
493              0.001995     0.000405              0.002674
494              0.001955     0.000376              0.002489
495              0.002078     0.000126              0.002648
496              0.002108     0.000194              0.002610
497              0.002101     0.000340              0.002524
498              0.002135     0.000324              0.002535
499              0.002090     0.000265              0.002385
500              0.001975     0.000216              0.002099
501              0.001719     0.000404              0.001572
502              0.001455     0.000330              0.001074
503              0.001206     0.000225              0.000643
504              0.000947     0.000184              0.000222
505              0.000606     0.000286             -0.000328
506              0.000436     0.000144             -0.000477
507              0.000207     0.000253             -0.000737
508             -0.000076     0.000343             -0.001091
509             -0.000241     0.000100             -0.001202
510             -0.000296    -0.000099             -0.001114
511             -0.000310    -0.000154             -0.000970
512             -0.000284    -0.000198             -0.000779
513             -0.000222    -0.000235             -0.000550
514             -0.000127    -0.000264             -0.000289
515              0.000000    -0.000289              0.000000

     value_ema_10_beta_98         volume
0                0.001281    7730.166667
1                0.001362    7730.166667
2                0.001404    7730.166667
3                0.001642    7730.166667
4                0.001969    7730.166667
5                0.001911    7730.166667
6                0.001648    7730.166667
7                0.001460   13497.000000
8                0.000792   48096.000000
9                0.000570    6033.000000
10               0.000484     100.000000
11               0.000478    3233.000000
12               0.000514    2136.000000
13               0.000379    7548.000000
14               0.000042   20206.000000
15              -0.000017   13067.000000
16               0.000320   18777.000000
17               0.000744    3652.000000
18               0.001177    6102.000000
19               0.001271   11455.000000
20               0.001081   24712.000000
21               0.001096    4717.000000
22               0.000875    5947.000000
23               0.000630   19697.000000
24               0.000513    2298.000000
25               0.000566   35676.000000
26               0.000463    6969.000000
27               0.000303   14515.000000
28              -0.000038   18867.000000
29              -0.000277       0.000000
..                    ...            ...
486              0.002051   18286.000000
487              0.002258    8453.000000
488              0.002430    5379.000000
489              0.002490   32438.000000
490              0.002457   19577.000000
491              0.002673   24223.000000
492              0.002725    9791.000000
493              0.002555   53196.000000
494              0.002376    2768.000000
495              0.002534   23569.000000
496              0.002508   19798.000000
497              0.002423   29717.000000
498              0.002428   10678.000000
499              0.002290    9859.000000
500              0.002033    3576.000000
501              0.001535   19371.000000
502              0.001064   27071.000000
503              0.000661   14994.000000
504              0.000266    6064.000000
505             -0.000261   26153.000000
506             -0.000413    6987.000000
507             -0.000680   13076.000000
508             -0.001043   47620.000000
509             -0.001166   30840.000000
510             -0.001089   15594.000000
511             -0.000954  495807.400000
512             -0.000771  495807.400000
513             -0.000547  495807.400000
514             -0.000289  495807.400000
515              0.000000  495807.400000

[516 rows x 9 columns]

In [70]:

from functools import reduce

# to order the columns in the order: last1,last2...last30, diff1, diff2,...diff30, value1, value2,...value30
def func(x):
    if 'timestamp' in x:
        return 0
    num = int(x.split('_')[-1])

    if 'last' in x:
        return 100 + num
    elif 'volume' in x:
        return 150 + num
    elif 'diff_ema_10' in x:
        return 200 + num
    elif 'diff_ema_20' in x:
        return 300 + num
    elif 'value_ema_10_beta_98' in x:
        return 400 + num
    elif 'value_ema_10_beta_99' in x:
        return 500 + num
    elif 'value_ema_20_beta_98' in x:
        return 600 + num
    elif 'value_ema_20_beta_99' in x:
        return 700 + num


def merge(df1, df2):
    global index
    merged = df1.set_index('timestamp').join(df2.set_index('timestamp'), how='outer')
    index += 1

    return merged.reset_index().rename({'index':'timestamp'}, axis=1)


columns_wanted = ['timestamp','last', 'diff_ema_20', 'value_ema_20_beta_99', 'value_ema_20_beta_98', 
           'diff_ema_10', 'value_ema_10_beta_99', 'value_ema_10_beta_98', 'volume']
df_day_list = []

for day_id in range(len(time_series_all_list[0])):
    print("processing day: {}".format(day_id))
    df_list = []
    for i in range(len(stock_id_list)):
        rename_map = {'last': 'last_' + str(i),
                      'diff_ema_20':'diff_ema_20_' + str(i),
                      'value_ema_20_beta_99':'value_ema_20_beta_99_' + str(i),
                      'value_ema_20_beta_98':'value_ema_20_beta_98_' + str(i),
                      'diff_ema_10':'diff_ema_10_' + str(i),
                      'value_ema_10_beta_99':'value_ema_10_beta_99_' + str(i),
                      'value_ema_10_beta_98':'value_ema_10_beta_98_'+ str(i),
                      'volume': 'volume_' + str(i)
                     }
        df = time_series_all_list[i][day_id][columns_wanted].rename(rename_map, axis=1)
        df_list.append(df)

    index = 0
    df_merged_daily = reduce(merge, df_list)
    columns = df_merged_daily.columns.tolist()
    columns.sort(key=func)
    df_merged_sorted = df_merged_daily[columns]
    
    df_day_list.append(df_merged_sorted)
    if day_id == 0:
        df_merged = df_merged_sorted
    else:
        df_merged = df_merged.append(df_merged_sorted)

processing day: 0
processing day: 1
processing day: 2
processing day: 3
processing day: 4
processing day: 5
processing day: 6
processing day: 7
processing day: 8
processing day: 9
processing day: 10
processing day: 11
processing day: 12
processing day: 13
processing day: 14
processing day: 15
processing day: 16
processing day: 17
processing day: 18
processing day: 19
processing day: 20
processing day: 21
processing day: 22
processing day: 23
processing day: 24
processing day: 25
processing day: 26
processing day: 27
processing day: 28
processing day: 29
processing day: 30
processing day: 31
processing day: 32
processing day: 33
processing day: 34
processing day: 35
processing day: 36
processing day: 37
processing day: 38
processing day: 39
processing day: 40
processing day: 41
processing day: 42
processing day: 43
processing day: 44
processing day: 45
processing day: 46
processing day: 47
processing day: 48
processing day: 49
processing day: 50
processing day: 51
processing day: 52
processing day: 53
processing day: 54
processing day: 55
processing day: 56
processing day: 57
processing day: 58
processing day: 59
processing day: 60
processing day: 61
processing day: 62

In [72]:
columns = df_merged_sorted.columns
last_columns = []
volume_columns = []
diff_ema_10_columns = []
diff_ema_20_columns = []
value_ema_10_beta_98_columns = []
value_ema_10_beta_99_columns = []
value_ema_20_beta_98_columns = []
value_ema_20_beta_99_columns = []
for item in columns:
    if 'last' in item:
        last_columns.append(item)
    elif 'volume' in item:
        volume_columns.append(item)
    elif 'diff_ema_10' in item:
        diff_ema_10_columns.append(item)
    elif 'diff_ema_20' in item:
        diff_ema_20_columns.append(item)
    elif 'value_ema_10_beta_98' in item:
        value_ema_10_beta_98_columns.append(item)
    elif 'value_ema_10_beta_99' in item:
        value_ema_10_beta_99_columns.append(item)
    elif 'value_ema_20_beta_98' in item:
        value_ema_20_beta_98_columns.append(item)
    elif 'value_ema_20_beta_99' in item:
        value_ema_20_beta_99_columns.append(item)

In [73]:
df_merged[['timestamp'] + volume_columns + last_columns + diff_ema_10_columns + value_ema_10_beta_98_columns].to_csv('data-prep-ema10-beta98.csv')
df_merged[['timestamp'] + volume_columns + last_columns + diff_ema_10_columns + value_ema_10_beta_99_columns].to_csv('data-prep-ema10-beta99.csv')
df_merged[['timestamp'] + volume_columns + last_columns + diff_ema_20_columns + value_ema_20_beta_98_columns].to_csv('data-prep-ema20-beta98.csv')
df_merged[['timestamp'] + volume_columns + last_columns + diff_ema_20_columns + value_ema_20_beta_99_columns].to_csv('data-prep-ema20-beta99.csv')